### ISSUE TITLE
promoter UI usability

### ISSUE THREAD

**Issue by xfyre** [danceconvention/dcnet-public#377]
* [x] error on a form tab doesn't show if the form tab is not active.
* [x] ~~and like before: this event stuff is the main thing, not something as a sub point of a sub point inside the profile of the user. the profile is normally only visited to change something (name, email, password, ....)~~ - being addressed by #366 
* [x] After creating/saving the event, I have no visual feedback that it actually was created/saved (since before I didn't see an error neither, I have no clue whether anything happened or there was a problem, especially since i'm staying int the form view)
* [x] ~~if i'm in "runtime" I have no way to get back to my event list except starting over, the breadcrumbs are kinda useless here (again, the issue of hiding everything inside the profile)~~ - already addressed by #366 
* [x] ~~instead of 3 lists of events, it would be nice to have 1 list, with filter buttons ( All | Participant | Judge | Promoter ) [ ] show past events for example~~ - already addressed by #366 
* [x] why does my staff has to signup first? Since they all have accounts already
* [x] what do the rights mean? 
* [x] what does the "quick access" button do? or is it a dropdown? (it shows the dropdown caret) (ah, later that menu is actually populated)
* [ ] in pricing policy: it's a add button dropdown? It's not clear what the dropdown entry means and it's not doing anything if you click. 
* [x] it's a lot of steps for very simple things at several places: add staff for example

**Comment by xfyre** [comment]
@e110c0 I've moved this from #366 as a separate issue

**Comment by xfyre** [comment]
@e110c0 Changes deployed to production. I'm not sure, however, about non-working dropdowns - it's not reproducible for me. If it's happening in a particular browser - please let me know what is it.
